# Generated by Django 4.2 on 2024-02-21 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='ambientes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_de_propiedad',
            field=models.CharField(choices=[[1, 'Departamento'], [2, 'Casa Country'], [3, 'Casa Residencial'], [4, 'Oficina'], [5, 'Proyecto de Construcción'], [6, 'Condominio'], [7, 'Comercio'], [8, 'Garage']], max_length=40),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='venta_o_alquiler',
            field=models.CharField(choices=[[1, 'Venta'], [2, 'Alquiler']], max_length=40),
        ),
    ]
