# Generated by Django 4.2 on 2024-02-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='otros_atributos',
            new_name='precio',
        ),
    ]
