# Generated by Django 4.2 on 2024-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appinmobiliaria",
            "0002_alter_propiedad_ambientes_alter_propiedad_banos_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="propiedad",
            old_name="banos",
            new_name="baños",
        ),
        migrations.RenameField(
            model_name="propiedad",
            old_name="localizacion",
            new_name="localidad",
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="descripcion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="tipo_de_propiedad",
            field=models.IntegerField(
                choices=[
                    [1, "Departamento"],
                    [2, "Casa Country"],
                    [3, "Casa Residencial"],
                    [4, "Oficina"],
                    [5, "Proyecto de Construcción"],
                    [6, "Condominio"],
                    [7, "Comercio"],
                    [8, "Garage"],
                ]
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="venta_o_alquiler",
            field=models.IntegerField(choices=[[1, "Venta"], [2, "Alquiler"]]),
        ),
    ]
